In [4]:
import gymnasium as gym
import numpy as np
env = gym.make("CartPole-v1", render_mode="human")

observation, info = env.reset(seed=42)
frame = []
for _ in range(500):
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)
    print(observation)
    frame.append(env.render())

    if terminated:
        observation, info = env.reset()
    if truncated:
        observation, info = env.reset()
        
env.close()

[ 0.02727336  0.18847767  0.03625453 -0.26141977]
[ 0.03104291  0.38306385  0.03102613 -0.5424507 ]
[ 0.03870419  0.1875199   0.02017712 -0.24015574]
[ 0.04245459  0.38234788  0.015374   -0.5264066 ]
[ 0.05010155  0.18701302  0.00484587 -0.22891912]
[ 0.05384181 -0.00817785  0.00026749  0.06528842]
[ 0.05367825 -0.20330364  0.00157326  0.35805574]
[ 0.04961218 -0.00820409  0.00873437  0.0658693 ]
[ 0.0494481  -0.20345017  0.01005176  0.36129513]
[ 0.04537909 -0.39871353  0.01727766  0.65713054]
[ 0.03740482 -0.5940717   0.03042027  0.9552034 ]
[ 0.02552339 -0.39937183  0.04952434  0.67223096]
[ 0.01753595 -0.20497201  0.06296896  0.39554295]
[ 0.01343651 -0.40092826  0.07087982  0.70739543]
[ 0.00541795 -0.59695685  0.08502772  1.0215211 ]
[-0.00652119 -0.40306428  0.10545815  0.7567011 ]
[-0.01458248 -0.5994694   0.12059217  1.0806193 ]
[-0.02657186 -0.40612793  0.14220455  0.8280815 ]
[-0.03469442 -0.6028779   0.1587662   1.1618949 ]
[-0.04675198 -0.7996706   0.1820041   1.4998528 ]


[ 0.13299984  0.9073879  -0.03752656 -0.90800124]
[ 0.1511476   0.7127935  -0.05568659 -0.6273453 ]
[ 0.16540347  0.5184912  -0.06823349 -0.35270706]
[ 0.1757733   0.7145138  -0.07528763 -0.66610175]
[ 0.19006357  0.5205152  -0.08860967 -0.3980419 ]
[ 0.20047387  0.7167752  -0.09657051 -0.71729404]
[ 0.21480937  0.91309154 -0.11091638 -1.0387442 ]
[ 0.23307121  0.7196042  -0.13169128 -0.78283924]
[ 0.2474633   0.91626644 -0.14734806 -1.1138837 ]
[ 0.2657886   1.1129831  -0.16962573 -1.448925  ]
[ 0.2880483   1.3097353  -0.19860423 -1.7894489 ]
[ 0.314243    1.1173191  -0.23439321 -1.5645045 ]
[ 0.02551783 -0.21031162  0.04785604  0.34646663]
[ 0.02131159 -0.40608048  0.05478538  0.653848  ]
[ 0.01318998 -0.21176244  0.06786234  0.3789071 ]
[ 0.00895474 -0.01766656  0.07544048  0.10836966]
[ 0.0086014  -0.21378396  0.07760787  0.4238675 ]
[ 0.00432572 -0.4099146   0.08608522  0.73997176]
[-0.00387257 -0.21608007  0.10088466  0.47557443]
[-0.00819417 -0.4124711   0.11039615  0.7982729 ]


[-0.16101062  0.14427388  0.1162533  -0.01507167]
[-0.15812515 -0.05230679  0.11595187  0.31191054]
[-0.15917128 -0.2488733   0.12219008  0.63879395]
[-0.16414875 -0.445468    0.13496596  0.9673219 ]
[-0.17305811 -0.6421188   0.1543124   1.2991751 ]
[-0.18590048 -0.44925523  0.1802959   1.0585054 ]
[-0.1948856  -0.6462477   0.20146601  1.4019247 ]
[-0.20781055 -0.45411676  0.2295045   1.1783884 ]
[ 0.02902214  0.2113069   0.021078   -0.25806686]
[ 0.03324828  0.4061217   0.01591666 -0.5440277 ]
[ 0.04137071  0.6010164   0.0050361  -0.8316534 ]
[ 0.05339104  0.40582597 -0.01159696 -0.5373909 ]
[ 0.06150756  0.601109   -0.02234478 -0.8337052 ]
[ 0.07352974  0.4062994  -0.03901888 -0.54813254]
[ 0.08165573  0.21174671 -0.04998153 -0.26799423]
[ 0.08589066  0.407545   -0.05534142 -0.5760134 ]
[ 0.09404156  0.21324071 -0.06686169 -0.3012652 ]
[ 0.09830637  0.40924877 -0.07288699 -0.61426306]
[ 0.10649135  0.6053094  -0.08517225 -0.92898303]
[ 0.11859754  0.4114341  -0.10375191 -0.6642346 ]


In [2]:
import gymnasium as gym
env = gym.make("MountainCarContinuous-v0", render_mode="human")

observation, info = env.reset(seed=42)
frame = []
for _ in range(500):
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)
    
    #frame.append(env.render())

    if terminated or truncated:
        observation, info = env.reset()
env.close()

In [3]:
np.array([1]).shape

(1,)

In [31]:
import torch

def policy()